---
- name: Deploy IaC configs to BGP routers
  hosts: rtr1,rtr2
  gather_facts: no
  pre_tasks:
    - name: Invoke Caretaker
      include_role:
        name: redhattelco.caretaker.caretaker
      vars:
        sot_repo: git@github.com:redhattelco/caretaker-sot.git
        running: "/running_configs/{{ inventory_hostname }}/running.cfg"
        archived: "/archived_configs/{{ inventory_hostname }}/config/running.cfg"

  tasks:

    - name: Update the Arista BGP configs
      arista.eos.eos_bgp:
        config: "{{ bgp_config }}"
        operation: replace
      when: ansible_network_os == 'eos'

    - name: Update the IOS BGP configs
      cisco.ios.ios_bgp:
        config: "{{ bgp_config }}"
        operation: replace
      when: ansible_network_os == 'eos'
