bgp_config:
  bgp_as: 65000
  #router_id: "{{ interfaces.interfaces_l3_config[0]['ipv4'] | ipaddr('network') }}"
  router_id: 192.168.2.2 #TODO replace with above later
  log_neighbor_changes: true
  address_family:
  neighbors:
    - neighbor: "{{ remote_public_ip }}"
      remote_as: 65000
  networks:
    - prefix: 10.25.25.0
      masklen: 24
    - prefix: 10.25.26.0
      masklen: 24
